### ISSUE TITLE
Sparkling Grid Dots not working properly in 'system' theme

### ISSUE THREAD

**Issue by ebulku** [nikhils4/ui-beats#19]
**Describe the bug**
Sparkling Grid not working properly when you are using the theme dynamically from next-themes since it can return also `system`, not only `light` or `dark`, I suggest using tailwind `dark:` selector instead of the having the theme as prop

**To Reproduce**
Have your system in darkmode and open the component doc page or UiBeats homepage with incognito without interacting with the dark-light mode button

**Comment by ebulku** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/9db34cad-b0d6-413b-8b21-21472c496e27)

**Comment by nikhils4** [comment]
Thanks for pointing it out @ebulku, will be fixing it soon, if reproducible 💯

**Comment by nikhils4** [comment]
Fixed with the recent commits (for other components as well). Thank you so much for highlighting this :)
